version: '3'
services:
  discoverme-db:
    container_name: discoverme-db
    image: postgres:latest
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      POSTGRES_DB: discoverme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dondot3056
      PGDATA: /data/postgres
    volumes:
      - ./config:/var/lib/postgresql/data
      - ./config/bootstrap-data.sql:/docker-entrypoint-initdb.d/bootstrap-data.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

#  discoverme:
#    container_name: discoverme
#    image: davidtega/discoverme:v1.0
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/discoverme
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=dondot3056
#    depends_on:
#      - discoverme-db
#    restart: unless-stopped

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    hostname: sonarqube
    depends_on:
      - discoverme-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://discoverme-db:5432/discoverme
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: dondot3056
    ports:
      - "9000:9000"

  pgadmin:
    container_name: discoverme-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - discoverme-db
    restart: unless-stopped

  jenkin:
    image: jenkins/jenkins:latest
    container_name: discoverme-jenkin
    volumes:
      - ./jenkin:/var/jenkins_home
    environment:
      JENKINS_HOST_HOME: "/jenkin"
    ports:
      - '8081:8080'
      - '50000:50000'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin