# fly.toml app configuration file generated for discoverme on 2023-09-05T11:24:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discoverme"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
