# fly.toml app configuration file generated for discoverme on 2023-08-28T16:52:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discoverme"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
